; Night Kernel
; Copyright 2015 - 2019 by mercury0x0d
; interrupts.inc is a part of the Night Kernel

; The Night Kernel is free software: you can redistribute it and/or modify it under the terms of the GNU General Public
; License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later
; version.

; The Night Kernel is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
; warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

; You should have received a copy of the GNU General Public License along with the Night Kernel. If not, see
; <http://www.gnu.org/licenses/>.

; See the included file <GPL License.txt> for the complete text of the GPL License by which this program is covered.





; variable definitions


; function definitions
extern CriticalError
extern IDTInit
extern InterruptHandlerGetAddress
extern InterruptHandlerGetFlags
extern InterruptHandlerGetSelector
extern InterruptHandlerSet
extern InterruptUnimplemented
extern ISRInitAll
extern ISR00
extern ISR01
extern ISR02
extern ISR03
extern ISR04
extern ISR05
extern ISR06
extern ISR07
extern ISR08
extern ISR09
extern ISR0A
extern ISR0B
extern ISR0C
extern ISR0D
extern ISR0E
extern ISR0F
extern ISR10
extern ISR11
extern ISR12
extern ISR13
extern ISR14
extern ISR15
extern ISR16
extern ISR17
extern ISR18
extern ISR19
extern ISR1A
extern ISR1B
extern ISR1C
extern ISR1D
extern ISR1E
extern ISR1F
extern ISR20
extern ISR21
extern ISR22
extern ISR23
extern ISR24
extern ISR25
extern ISR26
extern ISR27
extern ISR28
extern ISR29
extern ISR2A
extern ISR2B
extern ISR2C
extern ISR2D
extern ISR2E
extern ISR2F
