; Night Kernel
; Copyright 2015 - 2020 by mercury0x0d
; interrupts defines.inc is a part of the Night Kernel

; The Night Kernel is free software: you can redistribute it and/or modify it under the terms of the GNU General Public
; License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later
; version.

; The Night Kernel is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
; warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

; You should have received a copy of the GNU General Public License along with the Night Kernel. If not, see
; <http://www.gnu.org/licenses/>.

; See the included file <GPL License.txt> for the complete text of the GPL License by which this program is covered.





; declare variables as global
global kIDTPtr





; declare functions as global
global CriticalError
global IDTInit
global InterruptHandlerGetAddress
global InterruptHandlerGetFlags
global InterruptHandlerGetSelector
global InterruptHandlerSet
global InterruptUnimplemented
global ISRInitAll
global ISR00
global ISR01
global ISR02
global ISR03
global ISR04
global ISR05
global ISR06
global ISR07
global ISR08
global ISR09
global ISR0A
global ISR0B
global ISR0C
global ISR0D
global ISR0E
global ISR0F
global ISR10
global ISR11
global ISR12
global ISR13
global ISR14
global ISR15
global ISR16
global ISR17
global ISR18
global ISR19
global ISR1A
global ISR1B
global ISR1C
global ISR1D
global ISR1E
global ISR1F
global ISR20
global ISR21
global ISR22
global ISR23
global ISR24
global ISR25
global ISR26
global ISR27
global ISR28
global ISR29
global ISR2A
global ISR2B
global ISR2C
global ISR2D
global ISR2E
global ISR2F
