; Night Kernel
; Copyright 2015 - 2020 by mercury0x0d
; strings defines.inc is a part of the Night Kernel

; The Night Kernel is free software: you can redistribute it and/or modify it under the terms of the GNU General Public
; License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later
; version.

; The Night Kernel is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
; warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

; You should have received a copy of the GNU General Public License along with the Night Kernel. If not, see
; <http://www.gnu.org/licenses/>.

; See the included file <GPL License.txt> for the complete text of the GPL License by which this program is covered.





; declare functions as global
global ConvertByteToHexString16
global ConvertWordToHexString16
global ConvertNumberBinaryToString
global ConvertNumberDecimalToString
global ConvertNumberHexToString
global ConvertNumberOctalToString
global ConvertStringBinaryToNumber
global ConvertStringDecimalToNumber
global ConvertStringHexToNumber
global ConvertStringOctalToNumber
global StringCaseLower
global StringCaseUpper
global StringCharAppend
global StringCharDelete
global StringCharGet
global StringCharPrepend
global StringCharReplace
global StringCharReplaceRange
global StringFill
global StringInsert
global StringLength
global StringPadLeft
global StringPadRight
global StringSearchCharLeft
global StringSearchCharRight
global StringSearchCharList
global StringTokenBinary
global StringTokenDecimal
global StringTokenHexadecimal
global StringTokenOctal
global StringTokenString
global StringTrimLeft
global StringTrimRight
global StringTruncateLeft
global StringTruncateRight
global StringWordCount
global StringWordGet
