; Night Kernel
; Copyright 2015 - 2019 by mercury0x0d
; strings.inc is a part of the Night Kernel

; The Night Kernel is free software: you can redistribute it and/or modify it under the terms of the GNU General Public
; License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later
; version.

; The Night Kernel is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
; warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

; You should have received a copy of the GNU General Public License along with the Night Kernel. If not, see
; <http://www.gnu.org/licenses/>.

; See the included file <GPL License.txt> for the complete text of the GPL License by which this program is covered.







; function definitions
extern ConvertByteToHexString16
extern ConvertWordToHexString16
extern ConvertNumberBinaryToString
extern ConvertNumberDecimalToString
extern ConvertNumberHexToString
extern ConvertNumberOctalToString
extern ConvertStringBinaryToNumber
extern ConvertStringDecimalToNumber
extern ConvertStringHexToNumber
extern ConvertStringOctalToNumber
extern StringCaseLower
extern StringCaseUpper
extern StringCharAppend
extern StringCharDelete
extern StringCharGet
extern StringCharPrepend
extern StringCharReplace
extern StringCharReplaceRange
extern StringFill
extern StringInsert
extern StringLength
extern StringPadLeft
extern StringPadRight
extern StringSearchCharLeft
extern StringSearchCharRight
extern StringSearchCharList
extern StringTokenBinary
extern StringTokenDecimal
extern StringTokenHexadecimal
extern StringTokenOctal
extern StringTokenString
extern StringTrimLeft
extern StringTrimRight
extern StringTruncateLeft
extern StringTruncateRight
extern StringWordCount
extern StringWordGet
